/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cv.unicv.gpr.telas;

import cv.unicv.gpr.modelos.Funcionarios;
import cv.unicv.gpr.modelosdao.FuncionarioDAO;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author pc
 */
public final class FrmFuncionarios extends javax.swing.JFrame {

    /**
     * Creates new form fmrFazerPedido
     */
    
    public FrmFuncionarios() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) jTableFuncionarios.getModel();
        jTableFuncionarios.setRowSorter(new TableRowSorter(modelo));
        lerTable();
        
        
    }
    
    public void lerTable(){
        
        DefaultTableModel modelo = (DefaultTableModel) jTableFuncionarios.getModel();
        modelo.setNumRows(0);
        FuncionarioDAO funcionariodao = new FuncionarioDAO();
        
        for(Funcionarios f: funcionariodao.listar(this)){
            
            modelo.addRow(new Object[]{
                f.getIdFuncionarios(),
                f.getNome(),
                f.getCargo(),
                f.getDataNasc(),
                f.getSexo(),
                f.getMorada(),
                f.getTelefone(),
                f.getEmail(),
                f.getDataEntrada()
            });
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableFuncionarios = new javax.swing.JTable();
        btnAtualizar = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtPesquisar = new javax.swing.JTextField();
        btnPesquisar = new javax.swing.JButton();
        btnAdicionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(1024, 600));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel11.setBackground(new java.awt.Color(255, 204, 153));
        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestão de Funcionários", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 18))); // NOI18N
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setFont(new java.awt.Font("Berlin Sans FB", 0, 12)); // NOI18N

        jTableFuncionarios.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTableFuncionarios.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        jTableFuncionarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id ", "Nome", "Cargo", "Data Nascimento", "Sexo", "Morada", "Telefone", "Email", "Data de Entrada"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableFuncionarios.setGridColor(new java.awt.Color(255, 204, 153));
        jScrollPane2.setViewportView(jTableFuncionarios);

        jPanel11.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 970, 280));

        btnAtualizar.setBackground(new java.awt.Color(153, 255, 255));
        btnAtualizar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnAtualizar.setText("Atualizar");
        btnAtualizar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });
        jPanel11.add(btnAtualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 460, 90, 20));

        btnRemover.setBackground(new java.awt.Color(255, 153, 153));
        btnRemover.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnRemover.setText("Remover");
        btnRemover.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });
        jPanel11.add(btnRemover, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 460, 90, 20));

        jPanel2.setBackground(new java.awt.Color(255, 204, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Pesquisar Funcionarios", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 14), new java.awt.Color(153, 153, 153))); // NOI18N

        txtPesquisar.setFont(new java.awt.Font("Berlin Sans FB", 0, 13)); // NOI18N
        txtPesquisar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Berlin Sans FB", 0, 13), new java.awt.Color(153, 153, 153))); // NOI18N

        btnPesquisar.setBackground(new java.awt.Color(153, 255, 255));
        btnPesquisar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnPesquisar.setText("Pesquisar");
        btnPesquisar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 694, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 30, Short.MAX_VALUE)
                    .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel11.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 920, 80));

        btnAdicionar.setBackground(new java.awt.Color(153, 255, 255));
        btnAdicionar.setFont(new java.awt.Font("Berlin Sans FB", 0, 14)); // NOI18N
        btnAdicionar.setText("Adicionar");
        btnAdicionar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });
        jPanel11.add(btnAdicionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 90, 20));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 970, 500));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cv/unicv/gpr/icones/restaurant-1282 - Cópia.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 10, 80, 70));

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 600, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
        
        if (jTableFuncionarios.getSelectedRow() != -1) {
            
            Funcionarios func = new Funcionarios();
            
            func.setIdFuncionarios((int) jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 0));
            func.setNome((String) jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 1));
            func.setCargo((String) jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 2));
            func.setDataNasc((String) jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 3));
            func.setSexo((String) jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 4));
            func.setMorada((String) jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 5));
            func.setTelefone((int) jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 6));
            func.setEmail((String) jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 7));
            func.setDataEntrada((String) jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 8));
            
            JDialogAtualizarFuncionario jDialogAtualizarFuncionario = new JDialogAtualizarFuncionario(this, true, func);
            jDialogAtualizarFuncionario.setVisible(true);
        }
    }//GEN-LAST:event_btnAtualizarActionPerformed

    public void pesquisarTable(String palavraChave){
        
        DefaultTableModel modelo = (DefaultTableModel) jTableFuncionarios.getModel();
        modelo.setNumRows(0);
        FuncionarioDAO funcinoariodao = new FuncionarioDAO();
        
        for(Funcionarios f: funcinoariodao.pesquisar(palavraChave, this)){
            
            modelo.addRow(new Object[]{
                f.getIdFuncionarios(),
                f.getNome(),
                f.getCargo(),
                f.getDataNasc(),
                f.getSexo(),
                f.getMorada(),
                f.getTelefone(),
                f.getEmail(),
                f.getDataEntrada()
            });
        }
    }
    
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        // TODO add your handling code here:
        pesquisarTable(txtPesquisar.getText());

    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        // TODO add your handling code here:
        if (jTableFuncionarios.getSelectedRow() != -1) {
            
            Funcionarios f = new Funcionarios();
            FuncionarioDAO funcionario = new FuncionarioDAO();
            
            f.setIdFuncionarios((int) jTableFuncionarios.getValueAt(jTableFuncionarios.getSelectedRow(), 0));
                    
            funcionario.remover(f, this);
            
            lerTable();
        }
        
        if(jTableFuncionarios.getRowCount()==0) btnRemover.setVisible(false);
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
        JDialogAdicionarFuncionario jdialogAdicionarFuncionario = new JDialogAdicionarFuncionario(this, true);
        jdialogAdicionarFuncionario.setVisible(true);
    }//GEN-LAST:event_btnAdicionarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnRemover;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableFuncionarios;
    private javax.swing.JTextField txtPesquisar;
    // End of variables declaration//GEN-END:variables
}
